/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ArtistIdRouteImport } from './routes/artist.$id'
import { Route as GenreSlugRouteImport } from './routes/genre.$slug'
import { Route as PlaylistIdRouteImport } from './routes/playlist.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStorageUploadRouteImport } from './routes/api/storage/upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistIdRoute = ArtistIdRouteImport.update({
  id: '/artist/$id',
  path: '/artist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GenreSlugRoute = GenreSlugRouteImport.update({
  id: '/genre/$slug',
  path: '/genre/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistIdRoute = PlaylistIdRouteImport.update({
  id: '/playlist/$id',
  path: '/playlist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageUploadRoute = ApiStorageUploadRouteImport.update({
  id: '/api/storage/upload',
  path: '/api/storage/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/radio': typeof RadioRoute
  '/search': typeof SearchRoute
  '/studio': typeof StudioRoute
  '/artist/$id': typeof ArtistIdRoute
  '/genre/$slug': typeof GenreSlugRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/radio': typeof RadioRoute
  '/search': typeof SearchRoute
  '/studio': typeof StudioRoute
  '/artist/$id': typeof ArtistIdRoute
  '/genre/$slug': typeof GenreSlugRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/radio': typeof RadioRoute
  '/search': typeof SearchRoute
  '/studio': typeof StudioRoute
  '/artist/$id': typeof ArtistIdRoute
  '/genre/$slug': typeof GenreSlugRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/library'
    | '/login'
    | '/radio'
    | '/search'
    | '/studio'
    | '/artist/$id'
    | '/genre/$slug'
    | '/playlist/$id'
    | '/api/auth/$'
    | '/api/storage/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/library'
    | '/login'
    | '/radio'
    | '/search'
    | '/studio'
    | '/artist/$id'
    | '/genre/$slug'
    | '/playlist/$id'
    | '/api/auth/$'
    | '/api/storage/upload'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/library'
    | '/login'
    | '/radio'
    | '/search'
    | '/studio'
    | '/artist/$id'
    | '/genre/$slug'
    | '/playlist/$id'
    | '/api/auth/$'
    | '/api/storage/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  RadioRoute: typeof RadioRoute
  SearchRoute: typeof SearchRoute
  StudioRoute: typeof StudioRoute
  ArtistIdRoute: typeof ArtistIdRoute
  GenreSlugRoute: typeof GenreSlugRoute
  PlaylistIdRoute: typeof PlaylistIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStorageUploadRoute: typeof ApiStorageUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$id': {
      id: '/artist/$id'
      path: '/artist/$id'
      fullPath: '/artist/$id'
      preLoaderRoute: typeof ArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genre/$slug': {
      id: '/genre/$slug'
      path: '/genre/$slug'
      fullPath: '/genre/$slug'
      preLoaderRoute: typeof GenreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$id': {
      id: '/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof PlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/upload': {
      id: '/api/storage/upload'
      path: '/api/storage/upload'
      fullPath: '/api/storage/upload'
      preLoaderRoute: typeof ApiStorageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  RadioRoute: RadioRoute,
  SearchRoute: SearchRoute,
  StudioRoute: StudioRoute,
  ArtistIdRoute: ArtistIdRoute,
  GenreSlugRoute: GenreSlugRoute,
  PlaylistIdRoute: PlaylistIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStorageUploadRoute: ApiStorageUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
