/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RadioRouteImport } from './routes/radio'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WeeklyMixRouteImport } from './routes/weekly-mix'
import { Route as YouRouteImport } from './routes/you'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as ArtistIdRouteImport } from './routes/artist.$id'
import { Route as GenreSlugRouteImport } from './routes/genre.$slug'
import { Route as PlaylistIdRouteImport } from './routes/playlist.$id'
import { Route as TrackIdRouteImport } from './routes/track.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStorageUploadRouteImport } from './routes/api/storage/upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RadioRoute = RadioRouteImport.update({
  id: '/radio',
  path: '/radio',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeklyMixRoute = WeeklyMixRouteImport.update({
  id: '/weekly-mix',
  path: '/weekly-mix',
  getParentRoute: () => rootRouteImport,
} as any)
const YouRoute = YouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistIdRoute = ArtistIdRouteImport.update({
  id: '/artist/$id',
  path: '/artist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GenreSlugRoute = GenreSlugRouteImport.update({
  id: '/genre/$slug',
  path: '/genre/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistIdRoute = PlaylistIdRouteImport.update({
  id: '/playlist/$id',
  path: '/playlist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIdRoute = TrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStorageUploadRoute = ApiStorageUploadRouteImport.update({
  id: '/api/storage/upload',
  path: '/api/storage/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/radio': typeof RadioRoute
  '/search': typeof SearchRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/weekly-mix': typeof WeeklyMixRoute
  '/you': typeof YouRoute
  '/api/version': typeof ApiVersionRoute
  '/artist/$id': typeof ArtistIdRoute
  '/genre/$slug': typeof GenreSlugRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/track/$id': typeof TrackIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/radio': typeof RadioRoute
  '/search': typeof SearchRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/weekly-mix': typeof WeeklyMixRoute
  '/you': typeof YouRoute
  '/api/version': typeof ApiVersionRoute
  '/artist/$id': typeof ArtistIdRoute
  '/genre/$slug': typeof GenreSlugRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/track/$id': typeof TrackIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/radio': typeof RadioRoute
  '/search': typeof SearchRoute
  '/studio': typeof StudioRoute
  '/terms': typeof TermsRoute
  '/weekly-mix': typeof WeeklyMixRoute
  '/you': typeof YouRoute
  '/api/version': typeof ApiVersionRoute
  '/artist/$id': typeof ArtistIdRoute
  '/genre/$slug': typeof GenreSlugRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/track/$id': typeof TrackIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/storage/upload': typeof ApiStorageUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/explore'
    | '/library'
    | '/login'
    | '/privacy'
    | '/radio'
    | '/search'
    | '/studio'
    | '/terms'
    | '/weekly-mix'
    | '/you'
    | '/api/version'
    | '/artist/$id'
    | '/genre/$slug'
    | '/playlist/$id'
    | '/track/$id'
    | '/api/auth/$'
    | '/api/storage/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/explore'
    | '/library'
    | '/login'
    | '/privacy'
    | '/radio'
    | '/search'
    | '/studio'
    | '/terms'
    | '/weekly-mix'
    | '/you'
    | '/api/version'
    | '/artist/$id'
    | '/genre/$slug'
    | '/playlist/$id'
    | '/track/$id'
    | '/api/auth/$'
    | '/api/storage/upload'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/explore'
    | '/library'
    | '/login'
    | '/privacy'
    | '/radio'
    | '/search'
    | '/studio'
    | '/terms'
    | '/weekly-mix'
    | '/you'
    | '/api/version'
    | '/artist/$id'
    | '/genre/$slug'
    | '/playlist/$id'
    | '/track/$id'
    | '/api/auth/$'
    | '/api/storage/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExploreRoute: typeof ExploreRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RadioRoute: typeof RadioRoute
  SearchRoute: typeof SearchRoute
  StudioRoute: typeof StudioRoute
  TermsRoute: typeof TermsRoute
  WeeklyMixRoute: typeof WeeklyMixRoute
  YouRoute: typeof YouRoute
  ApiVersionRoute: typeof ApiVersionRoute
  ArtistIdRoute: typeof ArtistIdRoute
  GenreSlugRoute: typeof GenreSlugRoute
  PlaylistIdRoute: typeof PlaylistIdRoute
  TrackIdRoute: typeof TrackIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStorageUploadRoute: typeof ApiStorageUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radio': {
      id: '/radio'
      path: '/radio'
      fullPath: '/radio'
      preLoaderRoute: typeof RadioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekly-mix': {
      id: '/weekly-mix'
      path: '/weekly-mix'
      fullPath: '/weekly-mix'
      preLoaderRoute: typeof WeeklyMixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/you': {
      id: '/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof YouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$id': {
      id: '/artist/$id'
      path: '/artist/$id'
      fullPath: '/artist/$id'
      preLoaderRoute: typeof ArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genre/$slug': {
      id: '/genre/$slug'
      path: '/genre/$slug'
      fullPath: '/genre/$slug'
      preLoaderRoute: typeof GenreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$id': {
      id: '/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof PlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$id': {
      id: '/track/$id'
      path: '/track/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof TrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/storage/upload': {
      id: '/api/storage/upload'
      path: '/api/storage/upload'
      fullPath: '/api/storage/upload'
      preLoaderRoute: typeof ApiStorageUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExploreRoute: ExploreRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RadioRoute: RadioRoute,
  SearchRoute: SearchRoute,
  StudioRoute: StudioRoute,
  TermsRoute: TermsRoute,
  WeeklyMixRoute: WeeklyMixRoute,
  YouRoute: YouRoute,
  ApiVersionRoute: ApiVersionRoute,
  ArtistIdRoute: ArtistIdRoute,
  GenreSlugRoute: GenreSlugRoute,
  PlaylistIdRoute: PlaylistIdRoute,
  TrackIdRoute: TrackIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStorageUploadRoute: ApiStorageUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
